name: ruby

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: head
      - name: Test and lint
        run: |
          bundle
          bundle exec rake
          bundle exec standardrb
